image: node:latest

stages:
  - build
  - deploy

variables:
  IPFS_VERSION: v0.20.0

before_script:
  - apt-get update && apt-get install -y wget tar
  - wget https://dist.ipfs.tech/kubo/${IPFS_VERSION}/kubo_${IPFS_VERSION}_linux-amd64.tar.gz
  - tar -xvzf kubo_${IPFS_VERSION}_linux-amd64.tar.gz
  - cd kubo
  - ./install.sh
  - cd ..
  - ipfs init
  - ipfs daemon &

build:
  stage: build
  script:
    - commit_message=$(git log --format=%B -n 1 $CI_COMMIT_SHA)
    - echo "$commit_message"
    - >
      if echo "$commit_message" | grep -q "Deleting .upload"; then
        echo "Commit message contains 'Deleting .upload'. Skipping build and deploy."
        exit 0
      fi
    - npm install
    - npm run publish
    - npm run generate
    - rm kubo_${IPFS_VERSION}_linux-amd64.tar.gz
    - rm -r kubo
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "gitlab@ci-cd.com"
    - git checkout $CI_COMMIT_REF_NAME
    - git add --all
    - git commit -m "Update IPFS CAR and JSON files" || echo "No changes to commit"
    - git push -o ci-skip http://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master




deploy:
  stage: deploy
  script:
    - >
      if echo "$commit_message" | grep -q "Deleting .upload"; then
        echo "Commit message contains 'Deleting .upload'. Skipping deploy."
        exit 0
      fi
    - apt-get install -y rsync
    - rsync -avz --delete public/ $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public
