image: node:latest

stages:
  - build
  - deploy

variables:
  IPFS_VERSION: v0.20.0


    
pages:
  stage: deploy
  script:
    - commit_message=$(git log --format=%B -n 1 $CI_COMMIT_SHA)
    - echo "$commit_message"
    - |
      if echo "$commit_message" | grep -vq "complete"; then
        echo "Commit message does not contain 'complete'. Skipping build and deploy."
        exit 0
      fi

    - apt-get update && apt-get install -y wget tar
    - wget https://dist.ipfs.tech/kubo/${IPFS_VERSION}/kubo_${IPFS_VERSION}_linux-amd64.tar.gz
    - tar -xvzf kubo_${IPFS_VERSION}_linux-amd64.tar.gz
    - cd kubo
    - ./install.sh
    - cd ..
    - ipfs init
    - ipfs daemon &


    - npm install
    - npm run publish
    - npm run generate

  artifacts:
    paths:
      - public
      - ipfs