name: Docker Command on Commit

on:
  push:
    branches:
      - master
    paths:
      - 'backup/**'


jobs:
  docker_command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace node:latest sh -c "npm install -g ipfs-car && npx ipfs-car pack backup/ --output dist/ipfs.car"
